### PR TITLE
New Relay PullRequest5 [by sgrove]

### PR DESCRIPTION
**Pull request by sgrove**
Example body with egghead metadata and auto-appended title

```egghead-meta
{
  "lessonId": 3846,
  "filePath": "graphql-data-in-react-with-apollo-client/lessons/react-fetch-data-using-the-apollo-query-component.md",
  "username": "sgrove",
  "sha": "a2c4ab879f76cd3595ee7ac5a6ad1858024baf73"
}
```

### CODE REVIEW

**Comment by sgrove** [comment]
Comment test

**Comment by sgrove** [comment]
Another comment

**Comment by sgrove** [comment]
Third comment

**Comment by sgrove** [comment]
Fourth

**Comment by anmonteiro** [comment]
ahoy like a pirate

**Comment by sgrove** [comment]
As it should be.

**Pull request closed without merging**
